SYSTEM_CONFIG_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

if [[ -r "$SYSTEM_CONFIG_DIR/packages.conf" ]]; then
	# shellcheck disable=SC1090
	source "$SYSTEM_CONFIG_DIR/packages.conf"
fi